import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script"; // Import Script from Next.js

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add any other global meta or links here */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Add the TradingView script */}
        <Script
          src="https://s3.tradingview.com/tv.js"
          strategy="lazyOnload"
        />
        
        {/* TradingView widget container */}
        <div id="tradingview-widget"></div>
        
        {children}

        {/* Add the TradingView widget initialization */}
        <Script id="tradingview-widget-init" strategy="lazyOnload">
          {`
            new window.TradingView.widget({
              width: "100%",
              height: "400",
              symbol: "NASDAQ:AAPL",
              interval: "D",
              timezone: "Etc/UTC",
              theme: "light",
              style: "1",
              locale: "en",
              enable_publishing: false,
              container_id: "tradingview-widget"
            });
          `}
        </Script>
      </body>
    </html>
  );
}
